export const COLORS = [
    {colorName: 'Brown', 
     colorCode: '#9B720A',},
     {colorName: 'Black', 
     colorCode: '#000',},
     {colorName: 'Burgundy', 
     colorCode: '#5F021F',},
     {colorName: 'Blue', 
     colorCode: '#689ED0',},
     {colorName: 'Beige', 
     colorCode: '#E2D8BF',},
     {colorName: 'Brown', 
     colorCode: '#9B720A',},
     {colorName: 'Black', 
     colorCode: '#000',},
     {colorName: 'Burgundy', 
     colorCode: '#5F021F',},
     {colorName: 'Blue', 
     colorCode: '#689ED0',},
     {colorName: 'Beige', 
     colorCode: '#E2D8BF',},
     {colorName: 'Coral', 
     colorCode: '##F96F51',},
]